services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092  # Use 'kafka' as the advertised listener
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  # Allow unauthenticated connections
    networks:
      - kafka_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"  # Exposing PostgreSQL on 5433
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 10s
      retries: 5
    networks:
      - kafka_network

  hazelcast:
    image: hazelcast/hazelcast:latest
    ports:
      - "5701:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.network.tcpip.enabled=true -Dhazelcast.network.tcpip.members=127.0.0.1
    networks:
      - kafka_network

  user-managment-service:
    build:
      context: ./user-managment-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres  # Refer to db:5432 (inside Docker network)
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - KAFKA_URL=kafka:9092
      - JWT_SECRET_KEY=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      - JWT_EXPIRATION_TIME=3600000
      - HAZELCAST_NETWORK_TCPIP_ENABLED=true
      - HAZELCAST_NETWORK_TCPIP_MEMBERS=hazelcast:5701
    ports:
      - "8888:8888"
    depends_on:
      - kafka
      - db
      - hazelcast
    networks:
      - kafka_network

  order-managment-service:
    build:
      context: ./order-managment-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres  # Refer to db:5432 (inside Docker network)
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - KAFKA_BROKER_URL=kafka:9092
      - HAZELCAST_NETWORK_TCPIP_ENABLED=true
      - HAZELCAST_NETWORK_TCPIP_MEMBERS=hazelcast:5701
    ports:
      - "9999:9999"
    depends_on:
      - kafka
      - db
      - hazelcast
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge